services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: itau123
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: testBrianItau
      RABBITMQ_DEFAULT_PASS: itau123
    ports: ["5672:5672","15672:15672"]
    volumes: [rabbitmq_data:/var/lib/rabbitmq]
    healthcheck:
      test: ["CMD","rabbitmq-diagnostics","-q","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ./itau
      dockerfile: Dockerfile
    container_name: itau-app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: db_test
      DB_USER: test
      DB_PASS: itau123
      RABBITMQ_HOST: rabbitmq
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: itau-gateway
    depends_on:
      app:
        condition: service_started
    environment:
      TARGET_API_URI: http://app:8080
    ports: ["8081:8081"]
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmq_data:
