auth_enabled: false
server:
  http_listen_port: 3100
common:
  path_prefix: /loki
  retention_period: 168h  # 7 dias (ajuste conforme necessário)
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks
limits_config:
  ingestion_burst_size_mb: 64
  ingestion_rate_mb: 32
  max_streams_per_user: 0
  max_global_streams_per_user: 0
chunk_store_config:
  max_look_back_period: 336h
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
