server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}     # extrai campos padrão do log do Docker
      - json:
          expressions:
            level: level
            logger: logger
            thread: thread
            correlationId: correlationId
      - labels:
          level:
          logger:
          correlationId:
